version: "3.8"
services:
    db:
        container_name: buy_now_mongodb
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - dbdata6:/data/db
volumes:
    dbdata6:
